simulation:
  # simulation environment setup
  num_threads : 10
  FILE_ZERO_PADDING_NUM: 7
  use_gpu: True
  use_gpu_pipeline : False
  compute_device_id: 0
  graphics_device_id: 0
  physics_engine: PHYSX
  num_iters: 5
  num_envs: 120
  dt: 0.016667
  # camera: IntelRealSenseD415
  camera: IntelRealSenseD415IR
  # camera: ZividTwo

  # Asset setup
  # slider(dish mesh)
  slider_dataset: urdf
  # slider_name: takeout_cup_65oz
  # slider_name: bowl_0005
  # slider_name: melamineware_g_0001
  slider_name: mug_cup02
  # slider_name: scan_dish_4
  # Pusher
  pusher_dataset: pusher_urdf
  pusher_name: pusher_vertical

  # Push experiment setup
  push_speed: 0.1
  initial_distance: 0.1
  translational_push_distance: 0.01 # 0.01
  gripper_width: 0.08
  gripper_height: 0.018
  # gripper_height_max: 0.08
  gripper_angle: 90 # 0 ~ 90 [degree]
  rand_height: True
  rand_angle: True
  env_space: [1.6, 0.8]

  # Slider setup
  slider_rand_position_offset: [-0.05, 0.05] # [m, m]
  # slider_rand_position_offset: [-0.2, 0] # [m, m]
  # slider_rand_position_offset: [-0.45, 0] # [m, m]
  # slider_rand_position_range: [0, 0] # [%, %]
  # slider_rand_position_range: [0.05, 0.4] # [%, %]
  slider_rand_position_range: [0.4, 0.7] # [%, %]
  slider_rand_rotation_range: 180 # degrees 180
  camera_rand_position_range: 0 # meters 0.05
  camera_rand_rotation_range: 0 #degrees 10

  # contact point noise (offset)
  contact_offset_position_range: 0 # meters
  contact_offset_rotation_range: 0 # degrees

  # Labeling threshold
  threshold_pos: 0.01 # meters
  threshold_rot: 7 # degrees 15

  # Friction coefficients
  pusher_friction_coefficient: 0.1

  min_friction_coefficient: 0.8
  max_friction_coefficient: 1.2

camera:
  ZividTwo:
    fx: 1783.0662841796875
    fy: 1782.3050537109375
    cx: 980
    cy: 610.2705688476562

    camera_pose:
      x: -0.67 # meters 
      z: 0.95 # meters
      r: 13.5 # deg

  AzureKinect:
    depth:
      fx: 305.9728241
      fy: 305.94388962
      cx: 320.10463715
      cy: 244.73226547

    color:
      fx: 315.139
      fy: 236.372
      cx: 326.8280  
      cy: 245.1210

  IntelRealSenseD455:
    color:
      fx: 638.336669921875
      fy: 636.845703125
      cx: 630.5924072265625
      cy: 360.6282958984375

    depth:
      fx: 425.9282531738281
      fy: 425.9282531738281
      cx: 424.21240234375
      cy: 233.66128540039062

  IntelRealSenseD435:
    color:
      fx: 924.0841674804688
      fy: 924.6384887695312
      cx: 638.2789306640625
      cy: 373.99615478515625

    depth:
      fx: 924.0841674804688
      fy: 924.6384887695312
      cx: 638.2789306640625
      cy: 373.99615478515625
      
  IntelRealSenseD415:
    # fx: 1783.0662841796875
    # fy: 1782.3050537109375
    # cx: 980
    # cy: 610.2705688476562
    fx: 1367.0645751953125
    fy: 1365.3912353515625
    cx: 974.408203125
    cy: 528.857666015625
    
    color:
      fx: 1396.8086675255472
      fy: 1406.748094934653
      cx: 960
      cy: 540

    depth:
      fx: 520.3108903739
      fy: 189.709964
      cx: 960
      cy: 540

    camera_pose:
      # x: -1.08 # meters
      # z: 0.95 # meters
      # r: 10 # deg
      x: -0.5 # meters
      z: 3.5 # meters
      r: 0 # deg
      tran: [-1.081072195267972, 0.0030594282850760126, 0.9500685115443778]
      rot: [0.0032768099437612097, 0.9842047843130775, -0.015359940559485506, 0.17633569484891592]

  IntelRealSenseD415IR:
    fx: 893.821044921875
    fy: 893.821044921875
    cx: 633.1265258789062
    cy: 354.4530334472656

    # fx: 1367.0645751953125
    # fy: 1365.3912353515625
    # cx: 974.408203125
    # cy: 528.857666015625



    camera_pose:
      tran: [-1.0649844006838340, 0.095766369044197786, 0.95766369044197786]
      rot: [0.0032768099437612097, 0.9842047843130775, -0.015359940559485506, 0.17633569484891592]
      # rot: [-0.02431194, -2.83329651, 0.04357204]

      matrix: [ -9.5284142039327635e-01, 2.1412216810855048e-02, 3.0271231318558661e-01, -1.0649844006838340e+00,
        1.2093728749856781e-02, 9.9939450765343596e-01, -3.2624527537913145e-02, 9.5766369044197786e-02,
        -3.0322758665373545e-01, -2.7425080553976539e-02, -9.5252343574778220e-01, 9.5766369044197786e-01,
        0., 0., 0., 1. ]

      

      # [ -9.5284142039327635e-01, 2.1412216810855048e-02, 3.0271231318558661e-01, -1.0649844006838340e+00,
      #  1.2093728749856781e-02, 9.9939450765343596e-01, -3.2624527537913145e-02, 9.5766369044197786e-01,
      #  -3.0322758665373545e-01, -2.7425080553976539e-02, -9.5252343574778220e-01, 9.5766369044197786e-01,
      #   0., 0., 0., 1. ]
